"""
CTC-FA v2.0   --   L8 : horizon taxonomy engine.

The single most common category error in the popular and semi-technical
literature on time machines is the identification of *any* horizon with a
chronology horizon. v1.0 stated the taxonomy in a table (section 10) but
implemented only ``inverse_radial_horizon_candidates``, a solver for
``g^{rr} = 0``, which cannot distinguish the four objects at all.

v2.0 keeps them as separate computed objects, each with its own evidence and
its own forbidden shortcut:

    Killing horizon        a null hypersurface generated by a Killing field:
                           solved as ``g(xi, xi) = 0`` with ``d(g(xi,xi))``
                           null on the surface.
    Coordinate/metric      a locus where the chart degenerates: ``g^{rr} = 0``
    singularity            or ``det g = 0``, tested against curvature
                           invariants to separate chart failure from a real
                           singularity.
    Curvature              a locus where an invariant (Kretschmann) diverges.
    singularity
    Chronology horizon   the boundary of the chronology-violating set, which
                         in this architecture is computed from the reduced
                         causal margin, NOT inferred from any of the above.

Reissner-Nordstrom is the decisive control: it has an inner Cauchy horizon
and no chronology violation whatsoever. Misner is the converse: a
chronology horizon with no curvature singularity anywhere.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Sequence

import numpy as np
import sympy as sp

from .model import MetricModel
from .numerics import bracketed_bisection, coarse_sign_scan
from .symbolic import kretschmann


class HorizonKind(str, Enum):
    KILLING = "KILLING_HORIZON"
    COORDINATE_DEGENERACY = "COORDINATE_DEGENERACY"
    CURVATURE_SINGULARITY = "CURVATURE_SINGULARITY"
    CHRONOLOGY = "CHRONOLOGY_HORIZON"
    ERGOSURFACE = "ERGOSURFACE"


@dataclass
class HorizonCandidate:
    kind: HorizonKind
    equation: str
    solutions: list[str] = field(default_factory=list)
    numeric_roots: list[float] = field(default_factory=list)
    variable: str = ""
    note: str = ""
    forbidden_inference: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {"kind": self.kind.value, "equation": self.equation,
                "solutions": self.solutions, "numeric_roots": self.numeric_roots,
                "variable": self.variable, "note": self.note,
                "forbidden_inference": self.forbidden_inference}


FORBIDDEN = {
    HorizonKind.KILLING: "A Killing horizon is not an event horizon without a "
                         "global argument, and it is never a chronology horizon.",
    HorizonKind.COORDINATE_DEGENERACY:
        "A chart degeneracy is not a singularity and not a horizon; check a "
        "curvature invariant before drawing any conclusion.",
    HorizonKind.CURVATURE_SINGULARITY:
        "A curvature singularity is not a chronology horizon.",
    HorizonKind.ERGOSURFACE:
        "An ergosurface is where a coordinate direction stops being timelike; "
        "it is not a horizon and not a CTC boundary.",
    HorizonKind.CHRONOLOGY:
        "A chronology horizon must be derived from the causal margin, never "
        "inferred from any of the other objects in this table.",
}


def killing_horizon(model: MetricModel, index: int = 0,
                     variable: str = "r") -> HorizonCandidate:
    """Solve ``g(xi,xi) = 0`` for the coordinate Killing field ``d/dx^index``."""
    g = model.require_metric()
    expr = sp.simplify(g[index, index])
    try:
         var = model.symbol(variable)
         sols = sp.solve(sp.Eq(expr, 0), var)
    except Exception as exc:                              # noqa: BLE001
         sols, var = [], None
         expr = sp.sympify(f"solve failed: {exc}")
    return HorizonCandidate(
         HorizonKind.KILLING, f"g({model.coords[index]},{model.coords[index]}) "
                              f"= {expr} = 0",
         [str(s) for s in sols], [], variable,
         "null hypersurface generated by a coordinate Killing field, where the "
         "declared symmetry generator becomes null",
         FORBIDDEN[HorizonKind.KILLING])


def ergosurface(model: MetricModel, index: int = 0,
                variable: str = "r") -> HorizonCandidate:
    c = killing_horizon(model, index, variable)
    return HorizonCandidate(HorizonKind.ERGOSURFACE, c.equation, c.solutions,
                            c.numeric_roots, variable,
                            "locus where the reference Killing direction stops "
                            "being timelike",
                            FORBIDDEN[HorizonKind.ERGOSURFACE])


def coordinate_degeneracy(model: MetricModel,
                           variable: str = "r") -> HorizonCandidate:
    """Solve ``det g = 0`` and ``g^{rr} = 0``."""
    g = model.require_metric()
    det = sp.simplify(g.det())
    sols: list[str] = []
    try:
         var = model.symbol(variable)
         sols += [str(s) for s in sp.solve(sp.Eq(det, 0), var)]
         gi = g.inv()
         i = model.coord_index(variable)
         num, _ = sp.fraction(sp.cancel(sp.simplify(gi[i, i])))
         sols += [str(s) for s in sp.solve(sp.Eq(num, 0), var)]
    except Exception:                                     # noqa: BLE001
         pass
    return HorizonCandidate(
        HorizonKind.COORDINATE_DEGENERACY,
        f"det g = {det} = 0 and numerator(g^{{{variable}{variable}}}) = 0",
        sorted(set(sols)), [], variable,
        "chart degeneracy: must be tested against a curvature invariant",
        FORBIDDEN[HorizonKind.COORDINATE_DEGENERACY])


def curvature_singularities(model: MetricModel, variable: str = "r",
                             max_ops: int = 4000) -> HorizonCandidate:
    """Locate poles of the Kretschmann scalar (a genuine invariant)."""
    g = model.require_metric()
    try:
         K = kretschmann(g, model.coords, simplify=True)
    except Exception as exc:                              # noqa: BLE001
         return HorizonCandidate(HorizonKind.CURVATURE_SINGULARITY,
                                 f"K unavailable: {exc}", [], [], variable,
                                 "", FORBIDDEN[HorizonKind.CURVATURE_SINGULARITY])
    sols: list[str] = []
    try:
         var = model.symbol(variable)
         _, den = sp.fraction(sp.cancel(sp.together(K)))
         sols = [str(s) for s in sp.solve(sp.Eq(den, 0), var)]
    except Exception:                                     # noqa: BLE001
         pass
    return HorizonCandidate(
         HorizonKind.CURVATURE_SINGULARITY,
         f"denominator of K = R_abcd R^abcd vanishes; K = {sp.simplify(K)}",
         sorted(set(sols)), [], variable,
         "genuine curvature singularity: invariant, chart independent",
         FORBIDDEN[HorizonKind.CURVATURE_SINGULARITY])


def chronology_horizon(model: MetricModel, fixed: Mapping[str, float],
                        variable: str, lo: float, hi: float,
                        n: int = 512) -> HorizonCandidate:
    """Locate the chronology horizon as a zero of the reduced causal margin."""
    from .continuation import reduced_causal_margin_symbolic, reference_validity
    try:
         mu = reduced_causal_margin_symbolic(model)
         val = reference_validity(model)
    except ValueError as exc:
         return HorizonCandidate(HorizonKind.CHRONOLOGY, f"unavailable: {exc}",
                                 [], [], variable, "",
                                 FORBIDDEN[HorizonKind.CHRONOLOGY])
    var = model.symbol(variable)
    expr = mu.subs({model.symbol(k): v for k, v in fixed.items()})
    f = sp.lambdify(var, expr, "numpy")

    def q(x: float) -> float:
        with np.errstate(all="ignore"):
            v = float(f(x))
        return v if np.isfinite(v) else float("nan")

    fval = sp.lambdify(var, val.subs({model.symbol(k): v
                                      for k, v in fixed.items()}), "numpy")

    def reference_ok(x: float) -> bool:
        """Reject a zero of mu that is really a zero of the normalisation.

        mu = q/h has spurious roots wherever the timelike reference direction
        goes null. Misner's mu = -T(T+2) has such a root at T = -2 and a
        genuine chronology horizon at T = 0; without this filter the report
        would list both."""
        try:
             with np.errstate(all="ignore"):
                 return float(fval(x)) > 1e-8
        except Exception:                                # noqa: BLE001
             return True

    roots = []
    rejected = []
    for a, b in coarse_sign_scan(q, lo, hi, n=n):
        if a == b:
             (roots if reference_ok(a) else rejected).append(a)
             continue
        try:
             r, _, _ = bracketed_bisection(q, a, b, xtol=1e-13)
             (roots if reference_ok(r) else rejected).append(r)
        except ValueError:
             continue
    extra = (f"; {len(rejected)} root(s) rejected as normalisation artefacts "
              f"at {[round(x, 9) for x in rejected]}" if rejected else "")
    return HorizonCandidate(
        HorizonKind.CHRONOLOGY,
        f"reduced causal margin mu({variable}) = {sp.simplify(expr)} = 0",
        [], [float(r) for r in roots], variable,
        "boundary of the chronology-violating set, derived from the causal "
        "margin and from nothing else" + extra,
        FORBIDDEN[HorizonKind.CHRONOLOGY])


def horizon_report(model: MetricModel, variable: str = "r",
                   killing_index: int = 0,
                   chronology_range: tuple[float, float] | None = None,
                   fixed: Mapping[str, float] | None = None,
                   with_curvature: bool = True) -> dict[str, Any]:
    """Full L8 report: every object computed separately and labelled."""
    out: dict[str, Any] = {"model_id": model.id, "variable": variable,
                           "candidates": []}
    if not model.has_metric:
        out["note"] = "no local metric: horizon structure is external"
        return out
    has_var = any(str(c) == variable for c in model.coords)
    if has_var:
        out["candidates"].append(killing_horizon(model, killing_index, variable).as_dict())
        out["candidates"].append(coordinate_degeneracy(model, variable).as_dict())
        if with_curvature:
            out["candidates"].append(
                curvature_singularities(model, variable).as_dict())
    if chronology_range is not None and has_var:
        out["candidates"].append(chronology_horizon(
            model, fixed or {}, variable, *chronology_range).as_dict())
    out["taxonomy_rule"] = (
        "No entry in this report may be converted into another. In particular "
        "a Cauchy or Killing horizon is never, by itself, evidence of a "
        "chronology horizon (v1.0 REQ-006, FM-006).")
    return out


__all__ = ["HorizonKind", "HorizonCandidate", "killing_horizon", "ergosurface",
           "coordinate_degeneracy", "curvature_singularities",
           "chronology_horizon", "horizon_report", "FORBIDDEN"]
