"""
CTC-FA v2.0   --   L0 : the metric and construction registry.

Every entry declares, at minimum: coordinate ordering, signature, the metric
in the (-,+,+,+) convention, the parameter domain, the identification /
quotient structure, the matter content, the expected status *with its scope*,
and the literature reference the form was taken from.

Corrections applied to the v1.0 registry
---------------------------------------
D-01 Kerr ``g_t_phi``. The v1.0 registry table printed
      ``g_tphi = +2 M a r sin^2(theta) / Sigma`` while the v1.0 kernel used
      the negative sign. In Boyer-Lindquist coordinates with the (-,+,+,+)
      signature the correct component is

           g_t_phi = - 2 M a r sin^2(theta) / Sigma,

       because ds^2 contains ``-(4 M a r sin^2 theta / Sigma) dt dphi``. The
       kernel was right and the table was wrong; v2.0 fixes the table, and
       ``tests/unit/test_kerr_conventions.py`` pins the sign by checking the
       frame-dragging direction and the Kerr limit ``a -> 0``.

D-02   van Stockum symmetry. The v1.0 kernel built the van Stockum metric
       with the ``dt dphi`` term placed in one off-diagonal slot only, so
       ``g != g^T``. The compact-orbit detector reads only ``g_phi_phi`` and
       therefore still produced the published margin, which is why the defect
       survived the self-test, but every curvature, Einstein-tensor or
       geodesic computation on that model would have been wrong. v2.0 stores
       the symmetric form and ``MetricModel.assert_wellformed`` makes an
       asymmetric registry entry impossible to load.

D-06   Krasnikov regulator. The tube metric depends on a smooth-step
       regulator that is a numerical choice, not part of the exact solution.
       v2.0 marks the entry ``regulator_dependent`` so that no causal boundary
       may be derived from it.

D-07   Tipler / Ori-2007-full / Gott / paired-warp are ``EXTERNAL_EXACT_SPEC``
       or ``COMPOSITE_GLOBAL``: they have no canonical local 4x4 tensor and
       ``require_metric`` raises rather than returning an invented one.

New in v2.0
-----------
The ``ads4_universal_cover`` / ``ads4_periodic`` pair carries one identical
local metric and receives opposite global verdicts. It is the executable
proof of the L3 gate ("local equality of metrics does not imply equality of
global causal structure"), which v1.0 asserted but could not test.
``misner_covering`` and ``grant_space`` are flat quotients whose closed
curves are generated by a boost rather than by coordinate periodicity, and
are handled by the deck-orbit detector.
"""

from __future__ import annotations

import math
from typing import Mapping

import sympy as sp

from .model import (CompactDirection, DeckTransformation, DomainConstraint,
                    MatterSpec, MetricModel, Provenance, Quotient)
from .status import CTCStatus, ClaimScope, ModelKind

pi = sp.pi


def _dom(name: str, expr: sp.Expr, strict: bool = True, note: str = "") -> DomainConstraint:
    return DomainConstraint(name, sp.sympify(expr), strict, note)


# ==========================================================================
# M01 Minkowski
# ==========================================================================

def minkowski() -> MetricModel:
    t, x, y, z = sp.symbols("t x y z", real=True)
    g = sp.diag(-1, 1, 1, 1)
    return MetricModel(
        id="minkowski", title="M01 Minkowski spacetime",
        coords=(t, x, y, z), metric=g,
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("vacuum", T=sp.zeros(4, 4), vacuum=True),
        topology="R^4, simply connected",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.GLOBAL,
        temporal_function=t,
        default_point={"t": 0.0, "x": 1.0, "y": 0.0, "z": 0.0},
        domain_notes="Primary negative control for geometry, temporal-function "
                     "certification and tensor residual tests.",
        provenance=Provenance(("R26", "R28"), "signature (-,+,+,+)",
                              "flat metric by definition"),
        metadata={"role": "negative_control", "flat_covering": True})


# ==========================================================================
# M02 Spatially flat FLRW (symbolic scale factor)
# ==========================================================================

def flrw_flat() -> MetricModel:
    t, x, y, z = sp.symbols("t x y z", real=True)
    a = sp.Function("a", positive=True)(t)
    g = sp.diag(-1, a ** 2, a ** 2, a ** 2)
    return MetricModel(
        id="flrw_flat", title="M02 Spatially flat FLRW (general scale factor)",
        coords=(t, x, y, z), metric=g,
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("model-dependent cosmological matter"),
        topology="R x R^3 in the baseline chart",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.GLOBAL,
        temporal_function=t,
        domain_notes="Cosmic time t satisfies g^tt = -1 for ANY a(t) > 0, so the "
                     "temporal-function certificate is exact and scale-factor "
                     "independent. Tests that expansion and curvature alone do not "
                     "trigger a false CTC classification.",
        provenance=Provenance(("R26", "R27"), "signature (-,+,+,+)"),
        metadata={"role": "cosmological_control", "numeric_evaluable": False})


def flrw_exponential() -> MetricModel:
    t, x, y, z = sp.symbols("t x y z", real=True)
    H = sp.symbols("H", positive=True)
    a = sp.exp(H * t)
    g = sp.diag(-1, a ** 2, a ** 2, a ** 2)
    return MetricModel(
        id="flrw_exponential", title="M02b Spatially flat FLRW, a(t)=exp(H t)",
        coords=(t, x, y, z), params=(H,), metric=g,
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("de Sitter (Lambda = 3 H^2)", vacuum=True,
                          cosmological_constant=3 * H ** 2),
        topology="R x R^3 (flat slicing chart of de Sitter)",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.GLOBAL,
        temporal_function=t,
        default_point={"t": 0.0, "x": 1.0, "y": 0.0, "z": 0.0, "H": 1.0},
        domain_notes="Numerically evaluable companion to flrw_flat.",
        provenance=Provenance(("R26", "R27")),
        metadata={"role": "cosmological_control"})


# ==========================================================================
# M03 Schwarzschild
# ==========================================================================

def schwarzschild() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    M = sp.symbols("M", positive=True)
    f = 1 - 2 * M / r
    g = sp.diag(-f, 1 / f, r ** 2, r ** 2 * sp.sin(th) ** 2)
    return MetricModel(
        id="schwarzschild", title="M03 Schwarzschild",
        coords=(t, r, th, ph), params=(M,), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("vacuum", T=sp.zeros(4, 4), vacuum=True),
        topology="R^2 x S^2 exterior chart; phi ~ phi + 2 pi",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        temporal_function=t,
        domain=(_dom("exterior", r - 2 * M, True,
                     "the Schwarzschild t coordinate is a temporal function only "
                     "outside the horizon"),
                _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": 5.0, "theta": float(sp.pi / 2), "phi": 0.0, "M": 1.0},
        domain_notes="r = 2M is an event horizon, NOT a chronology horizon. "
                     "Separates horizon detection from causality violation.",
        provenance=Provenance(("R26", "R28"), "standard exterior chart"),
        metadata={"role": "negative_control", "horizon": "r = 2M",
                  "kretschmann": "48 M^2 / r^6"})


# ==========================================================================
# M04 Reissner-Nordstrom
# ==========================================================================

def reissner_nordstrom() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    M, Q = sp.symbols("M Q", real=True, positive=True)
    f = 1 - 2 * M / r + Q ** 2 / r ** 2
    g = sp.diag(-f, 1 / f, r ** 2, r ** 2 * sp.sin(th) ** 2)
    return MetricModel(
        id="reissner_nordstrom", title="M04 Reissner-Nordstrom",
        coords=(t, r, th, ph), params=(M, Q), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="Einstein-Maxwell",
        matter=MatterSpec("electrovacuum"),
        topology="phi ~ phi + 2 pi",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        temporal_function=t,
        domain=(_dom("outside_outer_horizon", r - (M + sp.sqrt(M ** 2 - Q ** 2)), True),
                _dom("subextremal", M ** 2 - Q ** 2, True),
                _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": 5.0, "theta": float(sp.pi / 2), "phi": 0.0,
                        "M": 1.0, "Q": 0.5},
        domain_notes="Critical negative control against the logical error "
                     "'Cauchy horizon implies CTC'. r_pm = M +- sqrt(M^2 - Q^2).",
        provenance=Provenance(("R26", "R28")),
        metadata={"role": "negative_control",
                  "cauchy_horizon": "r_- = M - sqrt(M^2 - Q^2)"})


# ==========================================================================
# M05 Kerr    (D-01 sign corrected)
# ==========================================================================

def kerr() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    M = sp.symbols("M", positive=True)
    a = sp.symbols("a", real=True)
    Sig = r ** 2 + a ** 2 * sp.cos(th) ** 2
    Del = r ** 2 - 2 * M * r + a ** 2
    gtt = -(1 - 2 * M * r / Sig)
    gtph = -2 * M * a * r * sp.sin(th) ** 2 / Sig           # D-01: negative
    gphph = sp.sin(th) ** 2 * (r ** 2 + a ** 2
                                + 2 * M * a ** 2 * r * sp.sin(th) ** 2 / Sig)
    g = sp.Matrix([[gtt, 0, 0, gtph],
                   [0, Sig / Del, 0, 0],
                   [0, 0, Sig, 0],
                   [gtph, 0, 0, gphph]])
    return MetricModel(
        id="kerr", title="M05 Kerr (Boyer-Lindquist)",
        coords=(t, r, th, ph), params=(M, a), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("vacuum away from the ring singularity", vacuum=True),
        topology="maximal analytic extension including r < 0; phi ~ phi + 2 pi",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("nondegenerate_Sigma", Sig, True),
                _dom("off_horizon", Del ** 2, True),
                _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": -0.5, "theta": float(sp.pi / 2), "phi": 0.0,
                        "M": 1.0, "a": 0.8},
        domain_notes="In part of the analytically extended r < 0 region "
                     "g_phi_phi < 0, so constant-(t,r,theta) azimuthal loops are "
                     "timelike. Mathematical existence; operational accessibility "
                     "and stability of that region are separate claims.",
        provenance=Provenance(("R3", "R26"),
                               "g_t_phi = -2 M a r sin^2(theta)/Sigma in (-,+,+,+); "
                               "the v1.0 registry table printed the opposite sign "
                               "(defect D-01)"),
        metadata={"role": "rotation_benchmark", "ctc_region": "r < 0 near theta = pi/2",
                  "sector_boundary": "g_phi_phi = 0"})


def kerr_extremal() -> MetricModel:
    m = kerr()
    M, a = m.symbol("M"), m.symbol("a")
    g = m.metric.subs(a, M)
    return MetricModel(
        id="kerr_extremal", title="M05b Extremal Kerr (a = M)",
        coords=m.coords, params=(M,), metric=g,
        compact=m.compact, kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("vacuum", vacuum=True),
        topology="phi ~ phi + 2 pi; degenerate horizon at r = M",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        default_point={"t": 0.0, "r": -0.5, "theta": float(sp.pi / 2), "phi": 0.0,
                        "M": 1.0},
        domain_notes="Extremal limit control: the CTC sector survives a -> M, so "
                     "the sector is not an artefact of subextremality.",
        provenance=Provenance(("R3", "R26")),
        metadata={"role": "limit_control"})


# ==========================================================================
# M06 Kerr-Newman
# ==========================================================================

def kerr_newman() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    M = sp.symbols("M", positive=True)
    a, Q = sp.symbols("a Q", real=True)
    Sig = r ** 2 + a ** 2 * sp.cos(th) ** 2
    A = 2 * M * r - Q ** 2
    Del = r ** 2 - 2 * M * r + a ** 2 + Q ** 2
    gtt = -(1 - A / Sig)
    gtph = -a * sp.sin(th) ** 2 * A / Sig
    gphph = sp.sin(th) ** 2 * (r ** 2 + a ** 2 + a ** 2 * sp.sin(th) ** 2 * A / Sig)
    g = sp.Matrix([[gtt, 0, 0, gtph],
                   [0, Sig / Del, 0, 0],
                   [0, 0, Sig, 0],
                   [gtph, 0, 0, gphph]])
    return MetricModel(
        id="kerr_newman", title="M06 Kerr-Newman",
        coords=(t, r, th, ph), params=(M, a, Q), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="Einstein-Maxwell",
        matter=MatterSpec("electrovacuum"),
        topology="maximal analytic extension; phi ~ phi + 2 pi",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("nondegenerate_Sigma", Sig, True),
                _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": -0.5, "theta": float(sp.pi / 2), "phi": 0.0,
                        "M": 1.0, "a": 0.8, "Q": -0.2},
        domain_notes="Tests multi-parameter continuation and the separation of "
                     "charge, rotation and causal pathology. Horizons exist when "
                     "M^2 >= a^2 + Q^2.",
        provenance=Provenance(("R26", "R28")),
        metadata={"role": "multiparameter_benchmark"})


# ==========================================================================
# M07/M08/M26 Godel-type hyperbolic family
# ==========================================================================

def godel_type() -> MetricModel:
    t, r, ph, z = sp.symbols("t r phi z", real=True)
    om, m = sp.symbols("omega m", positive=True)
    H = 4 * om / m ** 2 * sp.sinh(m * r / 2) ** 2
    D = sp.sinh(m * r) / m
    g = sp.Matrix([[-1, 0, -H, 0],
                   [0, 1, 0, 0],
                   [-H, 0, D ** 2 - H ** 2, 0],
                   [0, 0, 0, 1]])
    return MetricModel(
        id="godel_type", title="M07 Godel-type hyperbolic family (Rebouças-Tiomno)",
        coords=(t, r, ph, z), params=(om, m), metric=g,
        compact=(CompactDirection(2, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR or declared extension",
        matter=MatterSpec("source depends on the selected theory/matter model"),
        topology="R^3 x S^1 in the benchmark chart; phi ~ phi + 2 pi",
        expected=CTCStatus.UNRESOLVED, expected_scope=ClaimScope.SECTOR,
        expected_at_default=CTCStatus.CTC_PROVED,
        domain=(_dom("radial", r, True), _dom("rotation", om, True),
                _dom("scale", m, True)),
        default_point={"t": 0.0, "r": 2.0, "phi": 0.0, "z": 0.0,
                        "omega": 1.0, "m": 1.0},
        domain_notes="ds^2 = -[dt + H dphi]^2 + D^2 dphi^2 + dr^2 + dz^2 with "
                     "H = (4 omega/m^2) sinh^2(m r/2), D = sinh(m r)/m. "
                     "Circular CTCs exist for m^2 < 4 omega^2; the family is "
                     "causal for m^2 >= 4 omega^2. Primary analytic phase-boundary "
                     "benchmark.",
        provenance=Provenance(("R2", "R6"),
                               "Rebouças-Tiomno homogeneity classes"),
        metadata={"role": "phase_boundary_benchmark",
                  "normalised_sector_margin": "1 - (4 omega^2/m^2) tanh^2(m r/2)",
                  "exact_boundary": "m^2 = 4 omega^2",
                  "critical_radius": "sinh^2(m r_c/2) = [4 omega^2/m^2 - 1]^-1"})


def godel() -> MetricModel:
    base = godel_type()
    om, m = base.symbol("omega"), base.symbol("m")
    g = base.metric.subs(m, sp.sqrt(2) * om)
    return MetricModel(
        id="godel", title="M08 Godel solution (m^2 = 2 omega^2)",
        coords=base.coords, params=(om,), metric=sp.simplify(g),
        compact=base.compact, kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("dust + cosmological constant (original solution)"),
        topology=base.topology,
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("radial", base.symbol("r"), True), _dom("rotation", om, True)),
        default_point={"t": 0.0, "r": 2.0, "phi": 0.0, "z": 0.0, "omega": 1.0},
        domain_notes="Canonical exact CTC control. Finite critical radius "
                     "sinh^2(sqrt(2) omega r_c / 2) = 1, i.e. "
                     "r_c = 2 arcsinh(1)/(sqrt(2) omega).",
        provenance=Provenance(("R2", "R6"),
                              "special member of the hyperbolic Godel-type family"),
        metadata={"role": "exact_ctc_control",
                  "critical_radius_closed_form": "2*asinh(1)/(sqrt(2)*omega)"})


def godel_critical() -> MetricModel:
    base = godel_type()
    om, m, r = base.symbol("omega"), base.symbol("m"), base.symbol("r")
    g = sp.simplify(base.metric.subs(m, 2 * om))
    return MetricModel(
        id="godel_critical", title="M26 Critical Godel-type member (m^2 = 4 omega^2)",
        coords=base.coords, params=(om,), metric=g,
        compact=base.compact, kind=ModelKind.LOCAL_METRIC, theory="GR or extension",
        matter=MatterSpec("model-dependent"),
        topology=base.topology,
        expected=CTCStatus.UNRESOLVED, expected_scope=ClaimScope.SECTOR,
        domain=(_dom("radial", r, True), _dom("rotation", om, True)),
        default_point={"t": 0.0, "r": 2.0, "phi": 0.0, "z": 0.0, "omega": 1.0},
        domain_notes="Exactly on the causal phase boundary: the critical radius "
                     "diverges and g_phi_phi = sinh^2(2 omega r)/(4 omega^2) "
                     "* (1 - tanh^2) > 0 for all finite r. The azimuthal sector is "
                     "spacelike everywhere, but this is a SECTOR result only.",
        provenance=Provenance(("R2", "R6")),
        metadata={"role": "marginal_family_control"})


# ==========================================================================
# M09 van Stockum    (D-02 symmetry corrected)
# ==========================================================================

def van_stockum() -> MetricModel:
    t, r, ph, z = sp.symbols("t r phi z", real=True)
    a = sp.symbols("a", positive=True)
    emu = sp.exp(-a ** 2 * r ** 2)
    g = sp.Matrix([[-1, 0, a * r ** 2, 0],
                   [0, emu, 0, 0],
                   [a * r ** 2, 0, r ** 2 * (1 - a ** 2 * r ** 2), 0],
                   [0, 0, 0, emu]])
    return MetricModel(
        id="van_stockum", title="M09 van Stockum rotating dust interior",
        coords=(t, r, ph, z), params=(a,), metric=g,
        compact=(CompactDirection(2, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("rigidly rotating dust"),
        topology="cylindrical, z noncompact, phi ~ phi + 2 pi",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("radial", r, True), _dom("rotation", a, True)),
        default_point={"t": 0.0, "r": 2.0, "phi": 0.0, "z": 0.0, "a": 1.0},
        domain_notes="Azimuthal loops become timelike when r^2(1 - a^2 r^2) < 0, "
                     "i.e. a r > 1. Physical matching to an exterior at some "
                     "radius R is a separate constraint: the CTC region is present "
                     "only if a R > 1. v1.0 stored this metric asymmetrically "
                     "(defect D-02).",
        provenance=Provenance(("R7",), "Bonnor form of the van Stockum interior"),
        metadata={"role": "matter_supported_ctc", "exact_boundary": "a r = 1"})


# ==========================================================================
# M10 Tipler cylinder (external exact specification)
# ==========================================================================

def tipler_cylinder() -> MetricModel:
    return MetricModel(
        id="tipler_cylinder", title="M10 Tipler rotating cylinder construction",
        kind=ModelKind.EXTERNAL_EXACT_SPEC, theory="GR",
        topology="infinite rotating cylinder; exterior matched to a rotating interior",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.REDUCED_MODEL,
        domain_notes="Tipler showed causality violation for the idealised, "
                     "infinitely long, rapidly rotating cylinder. The exterior "
                     "depends on matching parameters; CTC-FA v2.0 refuses to "
                     "fabricate a single canonical local 4x4 tensor for it and "
                     "uses van Stockum for the explicit local interior benchmark.",
        provenance=Provenance(("R7",), external_spec="Tipler 1974 matched "
                                                     "van Stockum interior/exterior",
                              implementation_status="external"),
        metadata={"role": "overreach_control"})


# ==========================================================================
# M11 Lorentzian Taub-NUT
# ==========================================================================

def taub_nut() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    M, ell = sp.symbols("M ell", positive=True)
    f = (r ** 2 - 2 * M * r - ell ** 2) / (r ** 2 + ell ** 2)
    A = 2 * ell * sp.cos(th)
    g = sp.Matrix([[-f, 0, 0, -f * A],
                   [0, 1 / f, 0, 0],
                   [0, 0, r ** 2 + ell ** 2, 0],
                   [-f * A, 0, 0, -f * A ** 2 + (r ** 2 + ell ** 2) * sp.sin(th) ** 2]])
    return MetricModel(
        id="taub_nut", title="M11 Lorentzian Taub-NUT",
        coords=(t, r, th, ph), params=(M, ell), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("vacuum", vacuum=True),
        topology="phi periodic; the global time identification is "
                 "treatment-dependent (Misner string / Misner identification)",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.SECTOR,
        domain=(_dom("polar_regular", sp.sin(th), True),),
        default_point={"t": 0.0, "r": 3.0, "theta": 0.1, "phi": 0.0,
                        "M": 1.0, "ell": 1.0},
        domain_notes="Azimuthal CTC sectors occur where "
                     "-f (2 l cos theta)^2 + (r^2 + l^2) sin^2 theta < 0, i.e. near "
                     "the axis in the region f > 0. The local phi-loop detector does "
                     "NOT resolve the global identification choices; the verdict is "
                     "deliberately kept at SECTOR scope.",
        provenance=Provenance(("R26", "R28")),
        metadata={"role": "gravitomagnetic_pathology",
                  "sector_boundary": "g_phi_phi = 0"})


# ==========================================================================
# M12 Misner space (quotient chart) + M31 covering-space representation
# ==========================================================================

def misner() -> MetricModel:
    T, psi, y, z = sp.symbols("T psi y z", real=True)
    g = sp.Matrix([[0, -1, 0, 0],
                   [-1, -T, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]])
    return MetricModel(
        id="misner", title="M12 Misner space (quotient chart)",
        coords=(T, psi, y, z), metric=g,
        compact=(CompactDirection(1, "psi", 2 * pi),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR",
        matter=MatterSpec("flat vacuum locally", T=sp.zeros(4, 4), vacuum=True),
        topology="flat quotient; psi ~ psi + 2 pi; chronology horizon at T = 0",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        quotient=Quotient(
            generators=(DeckTransformation(
                "shift_psi", (T, psi + 2 * pi, y, z), (T, psi - 2 * pi, y, z),
                time_orientation_preserving=True,
                note="coordinate form of the boost identification"),),
            label="Z generated by psi -> psi + 2 pi", acts_freely=True),
        default_point={"T": 1.0, "psi": 0.0, "y": 0.0, "z": 0.0},
        reference_timelike=(sp.S.One, sp.S.One, sp.S.Zero, sp.S.Zero),
        domain_notes="det g = -1 everywhere, so the chart is regular across T = 0. "
                     "g_psi_psi = -T: compact psi loops are spacelike for T < 0, "
                     "null at T = 0 (the chronology horizon) and timelike for "
                     "T > 0. Cleanest benchmark separating local flatness from "
                     "global causal pathology.",
        provenance=Provenance(("R9", "R11", "R17")),
        metadata={"role": "chronology_horizon_benchmark",
                  "chronology_horizon": "T = 0", "flat_covering": True})


def misner_covering() -> MetricModel:
    """M31: Misner space as an explicit boost quotient of Minkowski.

    Independent representation of the same spacetime, used as a cross-check
    of the deck-orbit detector against the Misner-chart compact-orbit
    detector.
    """
    t, x, y, z = sp.symbols("t x y z", real=True)
    b = sp.symbols("b", positive=True)
    g = sp.diag(-1, 1, 1, 1)
    boost = DeckTransformation(
        "boost",
        (t * sp.cosh(b) + x * sp.sinh(b), t * sp.sinh(b) + x * sp.cosh(b), y, z),
        (t * sp.cosh(b) - x * sp.sinh(b), -t * sp.sinh(b) + x * sp.cosh(b), y, z),
        time_orientation_preserving=True,
        note="orthochronous boost of rapidity b in the (t,x) plane")
    return MetricModel(
        id="misner_covering", title="M31 Misner space as a boost quotient of Minkowski",
        coords=(t, x, y, z), params=(b,), metric=g,
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR",
        matter=MatterSpec("vacuum", T=sp.zeros(4, 4), vacuum=True),
        topology="Minkowski / <boost>; the quotient is Misner space",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        quotient=Quotient((boost,), label="Z generated by a boost", acts_freely=False,
                          note="the boost fixes the origin, so the quotient is taken "
                                "on the complement of the fixed axis"),
        domain=(_dom("off_axis", x ** 2 + t ** 2, True),),
        default_point={"t": 0.0, "x": 1.0, "y": 0.0, "z": 0.0, "b": 1.0},
        domain_notes="For the boost of rapidity b the invariant interval of the "
                     "closed geodesic through p and boost^n(p) is exactly "
                     "2 (cosh(n b) - 1) (t^2 - x^2). It is negative -- a CTC -- "
                     "precisely where x^2 > t^2, which is the image of the T > 0 "
                     "region of the Misner chart. This reproduces M12 from a "
                     "completely different representation.",
        provenance=Provenance(("R9", "R11"),
                              "Misner space as Minkowski modulo a boost"),
        metadata={"role": "cross_representation_check", "flat_covering": True,
                  "exact_orbit_interval": "2*(cosh(n*b)-1)*(t^2-x^2)"})


# ==========================================================================
# M27 Grant space
# ==========================================================================

def grant_space() -> MetricModel:
    t, x, y, z = sp.symbols("t x y z", real=True)
    b, alpha = sp.symbols("b alpha", positive=True)
    g = sp.diag(-1, 1, 1, 1)
    gen = DeckTransformation(
        "boost_translate",
        (t * sp.cosh(b) + x * sp.sinh(b), t * sp.sinh(b) + x * sp.cosh(b),
         y + alpha, z),
        (t * sp.cosh(b) - x * sp.sinh(b), -t * sp.sinh(b) + x * sp.cosh(b),
         y - alpha, z),
        time_orientation_preserving=True,
        note="boost of rapidity b in (t,x) composed with a translation alpha in y")
    return MetricModel(
        id="grant_space", title="M27 Grant space (boost + translation quotient)",
        coords=(t, x, y, z), params=(b, alpha), metric=g,
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR",
        matter=MatterSpec("vacuum", T=sp.zeros(4, 4), vacuum=True),
        topology="Minkowski / <boost x translation>",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        quotient=Quotient((gen,), label="Z generated by a screw isometry",
                           acts_freely=True,
                           note="the added translation removes the fixed axis, so the "
                                "action is free and the quotient is a manifold"),
        default_point={"t": 0.0, "x": 3.0, "y": 0.0, "z": 0.0, "b": 1.0, "alpha": 1.0},
        domain_notes="The invariant interval of the closed geodesic through p and "
                     "g^n(p) is exactly 2 (cosh(n b) - 1)(t^2 - x^2) + n^2 alpha^2. "
                     "The winding-n loop is null on the POLARISED HYPERSURFACE "
                     "x^2 - t^2 = n^2 alpha^2 / (2 (cosh(n b) - 1)) and timelike "
                     "outside it. Because that radius decreases monotonically to "
                     "zero as n grows, the union over all n is the whole region "
                     "x^2 > t^2: alpha > 0 does NOT move the chronology horizon, "
                     "which stays at x^2 = t^2 exactly as in Misner space. What "
                     "alpha creates is the discrete family of polarised "
                     "hypersurfaces that accumulates on the horizon, and those are "
                     "where the renormalised stress tensor of a quantum field is "
                     "singular. CTC-FA v2.0 locates them automatically from the "
                     "deck group; see quotient_ctc.polarized_hypersurfaces.",
        provenance=Provenance(("R9", "R11", "R17"),
                               "Grant 1993; Rieger 2026 causal classification"),
        metadata={"role": "polarised_quotient_benchmark", "flat_covering": True,
                  "chronology_horizon": "x^2 = t^2",
                  "polarized_hypersurface_n":
                      "x^2 - t^2 = n^2*alpha^2/(2*(cosh(n*b)-1))",
                  "exact_orbit_interval":
                      "2*(cosh(n*b)-1)*(t^2-x^2) + n^2*alpha^2"})


# ==========================================================================
# M13 Spinning cosmic string
# ==========================================================================

def spinning_cosmic_string() -> MetricModel:
    t, r, ph, z = sp.symbols("t r phi z", real=True)
    J, al = sp.symbols("J alpha", positive=True)
    g = sp.Matrix([[-1, 0, -4 * J, 0],
                   [0, 1, 0, 0],
                   [-4 * J, 0, al ** 2 * r ** 2 - 16 * J ** 2, 0],
                   [0, 0, 0, 1]])
    return MetricModel(
        id="spinning_cosmic_string", title="M13 Spinning cosmic string",
        coords=(t, r, ph, z), params=(J, al), metric=g,
        compact=(CompactDirection(2, "phi", 2 * pi),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR with a distributional source",
        matter=MatterSpec("distributional string source on the axis"),
        topology="conical quotient; phi ~ phi + 2 pi; deficit angle 2 pi (1 - alpha)",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("radial", r, True), _dom("cone_angle", al, True),
                _dom("spin", J, True)),
        default_point={"t": 0.0, "r": 0.1, "phi": 0.0, "z": 0.0,
                        "J": 0.1, "alpha": 0.8},
        domain_notes="ds^2 = -(dt + 4J dphi)^2 + dr^2 + alpha^2 r^2 dphi^2 + dz^2. "
                     "g_phi_phi = alpha^2 r^2 - 16 J^2 < 0 gives azimuthal CTCs "
                     "inside r < 4J/alpha in the idealised model.",
        provenance=Provenance(("R8", "R26")),
        metadata={"role": "conical_quotient_benchmark",
                  "exact_boundary": "alpha^2 r^2 = 16 J^2"})


# ==========================================================================
# M14 Gott two-string construction
# ==========================================================================

def gott_two_strings() -> MetricModel:
    def margin(p: Mapping[str, float]) -> float:
        mu = float(p["mu"])
        v = float(p["v"])
        if not (0.0 < v < 1.0):
            raise ValueError("Gott predicate requires 0 < v < 1")
        arg = 4.0 * math.pi * mu
        if not (0.0 < arg < math.pi):
            raise ValueError("Gott predicate requires 0 < 4 pi mu < pi")
        gamma = 1.0 / math.sqrt(1.0 - v * v)
        return 1.0 / math.sin(arg) - gamma

    return MetricModel(
        id="gott_two_strings", title="M14 Gott two-moving-cosmic-string construction",
        kind=ModelKind.COMPOSITE_GLOBAL, theory="GR with distributional sources",
        topology="global holonomy around two non-intersecting infinite string defects",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.REDUCED_MODEL,
        default_point={"mu": 0.01, "v": 0.999},
        global_margin=margin, global_margin_scope=ClaimScope.REDUCED_MODEL,
        global_margin_note="CTCs exist when gamma > 1/sin(4 pi mu), equivalently "
                           "gamma v > cot(4 pi mu). Only the published global "
                           "holonomy criterion is evaluated; no local metric is "
                           "asserted.",
        domain_notes="Tests global holonomy criteria and prevents local-metric "
                     "overreach. mu here is G mu / c^2, so the deficit angle is "
                     "8 pi mu.",
        provenance=Provenance(("R8", "R9"),
                              external_spec="Gott 1991 exact two-string solution"),
        metadata={"role": "global_holonomy_benchmark",
                  "equivalent_forms": ["gamma > 1/sin(4 pi mu)",
                                        "gamma v > cot(4 pi mu)"]})


# ==========================================================================
# M15 Morris-Thorne
# ==========================================================================

def morris_thorne() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    r0 = sp.symbols("r0", positive=True)
    b = r0 ** 2 / r
    g = sp.diag(-1, 1 / (1 - b / r), r ** 2, r ** 2 * sp.sin(th) ** 2)
    return MetricModel(
        id="morris_thorne", title="M15 Morris-Thorne zero-redshift wormhole",
        coords=(t, r, th, ph), params=(r0,), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("exotic: NEC is violated near the throat under standard "
                           "GR assumptions"),
        topology="two asymptotic regions joined by a throat; phi ~ phi + 2 pi",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        temporal_function=t,
        domain=(_dom("outside_throat", r - r0, False,
                     "r >= r0; the r-chart is singular exactly at the throat"),
                _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": 2.0, "theta": float(sp.pi / 2), "phi": 0.0,
                        "r0": 1.0},
        domain_notes="Phi = 0 and b(r) = r0^2/r. A static traversable wormhole is "
                     "NOT automatically a time machine: g^tt = -1 so t is an exact "
                     "temporal function on this chart. Throat b(r0) = r0, "
                     "flare-out b'(r0) = -1 < 1.",
        provenance=Provenance(("R4", "R5", "R18")),
        metadata={"role": "topology_vs_chronology_control",
                  "throat": "r = r0", "flare_out": "b'(r0) = -1"})


# ==========================================================================
# M16 Time-shifted wormhole (reduced route-closure model)
# ==========================================================================

def time_shifted_wormhole() -> MetricModel:
    def margin(p: Mapping[str, float]) -> float:
        return float(p["t_ext"]) + float(p["t_wh"]) - abs(float(p["delta_t"]))

    return MetricModel(
        id="time_shifted_wormhole", title="M16 Time-shifted traversable wormhole "
                                          "(reduced route-closure model)",
        kind=ModelKind.COMPOSITE_GLOBAL, theory="GR (assumed traversable wormhole)",
        topology="two mouths with a nontrivial spacetime identification",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.REDUCED_MODEL,
        default_point={"delta_t": 12.0, "t_ext": 10.0, "t_wh": 1.0},
        global_margin=margin, global_margin_scope=ClaimScope.REDUCED_MODEL,
        global_margin_note="margin = t_ext + t_wh - |Delta t|. Negative margin "
                           "means the declared route closes to the past. This is an "
                           "ARCHITECTURE-SPECIFIC reduced predicate under declared "
                           "synchronisation and traversal assumptions, NOT a "
                           "universal theorem for arbitrary dynamical wormholes. A "
                           "production model must compute causal travel times from "
                           "the full metric and the mouth worldlines.",
        domain_notes="Explicitly labelled reduced criterion, used for software "
                     "regression and parameter continuation. Requires: external "
                     "travel time t_ext between mouths, wormhole traversal time "
                     "t_wh, accumulated mouth time shift Delta t, all in one "
                     "declared synchronisation.",
        provenance=Provenance(("R5", "R18", "R19"),
                              external_spec="Morris-Thorne-Yurtsever time-machine "
                                            "argument"),
        metadata={"role": "reduced_predicate_benchmark"})


# ==========================================================================
# M17 Ori 2005 compact vacuum core
# ==========================================================================

def ori_2005() -> MetricModel:
    T, x, y, z = sp.symbols("T x y z", real=True)
    F = x ** 2 - y ** 2
    g = sp.Matrix([[0, 0, 0, -1],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [-1, 0, 0, F - T]])
    return MetricModel(
        id="ori_2005", title="M17 Ori 2005 compact vacuum-core chart",
        coords=(T, x, y, z), metric=g,
        compact=(CompactDirection(3, "z", sp.Symbol("L", positive=True)),),
        params=(sp.Symbol("L", positive=True),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR",
        matter=MatterSpec("vacuum core; surrounding matter in the full Ori model "
                          "satisfies WEC, DEC and SEC", T=sp.zeros(4, 4), vacuum=True),
        topology="z periodically identified with period L",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        default_point={"T": 1.0, "x": 0.0, "y": 0.0, "z": 0.0, "L": 1.0},
        reference_timelike=(sp.S.One, sp.S.Zero, sp.S.Zero, sp.S.One),
        domain_notes="ds^2 = dx^2 + dy^2 - 2 dT dz + [F(x,y) - T] dz^2 with the "
                     "harmonic benchmark F = x^2 - y^2 (Laplacian zero, so the core "
                     "is vacuum). At fixed (x,y) the compact z direction changes "
                     "from spacelike to timelike when F - T crosses zero. This is "
                     "the decisive counterexample to any universal rule "
                     "'CTC implies NEC violation'.",
        provenance=Provenance(("R14",)),
        metadata={"role": "energy_condition_counterexample",
                  "exact_boundary": "T = F(x,y)"})


# ==========================================================================
# M18 Ori 2007 periodic pseudo-Schwarzschild core
# ==========================================================================

def ori_2007_core() -> MetricModel:
    v, r, th, ph = sp.symbols("v r theta phi", real=True)
    mu, P = sp.symbols("mu P", positive=True)
    f = 1 - 2 * mu / r
    g = sp.Matrix([[f, 1, 0, 0],
                   [1, 0, 0, 0],
                   [0, 0, r ** 2, 0],
                   [0, 0, 0, r ** 2 * sp.sinh(th) ** 2]])
    return MetricModel(
        id="ori_2007_core", title="M18 Ori 2007 periodic pseudo-Schwarzschild core",
        coords=(v, r, th, ph), params=(mu, P), metric=g,
        compact=(CompactDirection(0, "v", P),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR",
        matter=MatterSpec("vacuum core", T=sp.zeros(4, 4), vacuum=True),
        topology="v periodically identified in the internal core",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("radial", r, True), _dom("hyperbolic_regular", sp.sinh(th), True)),
        default_point={"v": 0.0, "r": 1.0, "theta": 1.0, "phi": 0.0, "mu": 1.0,
                        "P": 1.0},
        reference_timelike=(sp.S.One, -sp.S.One, sp.S.Zero, sp.S.Zero),
        domain_notes="ds^2 = (1 - 2 mu/r) dv^2 + 2 dv dr + r^2 (dtheta^2 + "
                     "sinh^2(theta) dphi^2). The 2-surfaces are hyperbolic, not "
                     "spherical. Periodic v loops become timelike for r < 2 mu; "
                     "r = 2 mu is marginal. Benchmark for constructibility from "
                     "regular initial data.",
        provenance=Provenance(("R15", "R17")),
        metadata={"role": "constructibility_benchmark", "exact_boundary": "r = 2 mu"})


def pseudo_reissner_nordstrom() -> MetricModel:
    """M32: charged Rieger-type pseudo-RN core, the natural two-parameter
    extension of ``ori_2007_core``. Gives a second analytic causal boundary
    with a closed form, used as an independent continuation test."""
    v, r, th, ph = sp.symbols("v r theta phi", real=True)
    mu, q, P = sp.symbols("mu q P", positive=True)
    f = 1 - 2 * mu / r + q ** 2 / r ** 2
    g = sp.Matrix([[f, 1, 0, 0],
                   [1, 0, 0, 0],
                   [0, 0, r ** 2, 0],
                   [0, 0, 0, r ** 2 * sp.sinh(th) ** 2]])
    return MetricModel(
        id="pseudo_reissner_nordstrom",
        title="M32 Periodic pseudo-Reissner-Nordstrom core (Rieger-type)",
        coords=(v, r, th, ph), params=(mu, q, P), metric=g,
        compact=(CompactDirection(0, "v", P),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="Einstein-Maxwell (pseudo-spherical)",
        matter=MatterSpec("electrovacuum core"),
        topology="v periodically identified",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("radial", r, True), _dom("subextremal", mu ** 2 - q ** 2, True),
                _dom("hyperbolic_regular", sp.sinh(th), True)),
        default_point={"v": 0.0, "r": 1.0, "theta": 1.0, "phi": 0.0,
                       "mu": 1.0, "q": 0.5, "P": 1.0},
        reference_timelike=(sp.S.One, -sp.S.One, sp.S.Zero, sp.S.Zero),
        domain_notes="Periodic v loops are timelike exactly between the roots "
                     "r_pm = mu +- sqrt(mu^2 - q^2) of f(r). Two-parameter analytic "
                     "boundary for the continuation engine, structurally parallel "
                     "to Reissner-Nordstrom but with an opposite causal meaning: "
                     "here the roots bound a genuine chronology-violating region.",
        provenance=Provenance(("R15", "R17"),
                              "charged extension of the Ori-2007 pseudo-Schwarzschild "
                              "core in the Rieger classification programme"),
        metadata={"role": "two_parameter_boundary",
                  "exact_boundary": "r = mu +- sqrt(mu^2 - q^2)"})


def ori_2007_full() -> MetricModel:
    return MetricModel(
        id="ori_2007_full", title="M19 Ori 2007 full composite model",
        kind=ModelKind.EXTERNAL_EXACT_SPEC, theory="GR",
        topology="compact vacuum core + positive-density dust envelope + "
                 "asymptotically flat vacuum exterior",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.REDUCED_MODEL,
        domain_notes="Closed timelike curves form after evolution from a regular "
                     "spacelike initial hypersurface in the published model, with "
                     "WEC, DEC and SEC satisfied. Highest-value target for a full "
                     "ADM/evolution reproduction; the matching and initial data are "
                     "a separate implementation.",
        provenance=Provenance(("R15",),
                              external_spec="Ori 2007 composite vacuum/dust "
                                            "asymptotically flat model",
                              implementation_status="external"),
        metadata={"role": "constructibility_target"})


# ==========================================================================
# M20 Alcubierre
# ==========================================================================

def alcubierre() -> MetricModel:
    t, x, y, z = sp.symbols("t x y z", real=True)
    v, R, sig = sp.symbols("v R sigma", positive=True)
    xs = v * t
    rs = sp.sqrt((x - xs) ** 2 + y ** 2 + z ** 2)
    f = (sp.tanh(sig * (rs + R)) - sp.tanh(sig * (rs - R))) / (2 * sp.tanh(sig * R))
    g = sp.Matrix([[-1 + v ** 2 * f ** 2, -v * f, 0, 0],
                   [-v * f, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]])
    return MetricModel(
        id="alcubierre", title="M20 Alcubierre warp metric",
        coords=(t, x, y, z), params=(v, R, sig), metric=g,
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("violates the classical energy conditions"),
        topology="R^4 single-bubble chart, no identifications",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        temporal_function=t,
        default_point={"t": 0.0, "x": 1.0, "y": 0.0, "z": 0.0,
                        "v": 2.0, "R": 1.0, "sigma": 8.0},
        domain_notes="ds^2 = -dt^2 + [dx - v f(r_s) dt]^2 + dy^2 + dz^2. A single "
                     "bubble is not automatically a CTC: t is an exact temporal "
                     "function on this chart (g^tt = -1), so causality violation "
                     "requires an additional global or multi-bubble arrangement. "
                     "Prevents equating effective superluminality with a time "
                     "machine.",
        provenance=Provenance(("R12",)),
        metadata={"role": "superluminality_control"})


# ==========================================================================
# M21 Krasnikov tube
# ==========================================================================

def krasnikov() -> MetricModel:
    t, x, rho, ph = sp.symbols("t x rho phi", real=True)
    delta, eps, rho_max, D = sp.symbols("delta epsilon rho_max D", positive=True)

    def step(q):
        return (1 + sp.tanh(q / eps)) / 2

    k = 1 - (2 - delta) * step(rho_max - rho) * step(t - x - rho) * step(x + eps - D)
    g = sp.Matrix([[-1, 1 - k, 0, 0],
                   [1 - k, k * (2 - k), 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, rho ** 2]])
    return MetricModel(
        id="krasnikov", title="M21 Krasnikov tube (Everett-Roman form)",
        coords=(t, x, rho, ph), params=(delta, eps, rho_max, D), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR",
        matter=MatterSpec("requires exotic stress-energy in standard GR"),
        topology="phi periodic only; a CTC requires a suitable multi-tube "
                 "or global arrangement",
        expected=CTCStatus.UNRESOLVED, expected_scope=ClaimScope.SECTOR,
        domain=(_dom("radial", rho, True),),
        default_point={"t": 20.0, "x": 5.0, "rho": 0.1, "phi": 0.0,
                        "delta": 0.1, "epsilon": 0.1, "rho_max": 1.0, "D": 10.0},
        domain_notes="ds^2 = -dt^2 + 2(1-k) dt dx + k(2-k) dx^2 + drho^2 + "
                     "rho^2 dphi^2. The (t,x) block has determinant exactly -1 for "
                     "every k, so the chart is Lorentzian everywhere. A single tube "
                     "is not itself a time machine. The smooth step is a REGULATOR "
                     "CHOICE, not part of an exact solution, so no causal boundary "
                     "may be derived from this entry (defect D-06).",
        provenance=Provenance(("R13",),
                               "Everett-Roman smooth-step implementation of "
                               "Krasnikov's tube"),
        metadata={"role": "shortcut_vs_loop_control", "regulator_dependent": True})


# ==========================================================================
# M22 Paired warp / superluminal causal-loop family
# ==========================================================================

def paired_warp() -> MetricModel:
    return MetricModel(
        id="paired_warp", title="M22 Paired warp / superluminal causal-loop family",
        kind=ModelKind.COMPOSITE_GLOBAL, theory="construction-specific",
        topology="multi-segment engineered spacetime with global route closure",
        expected=CTCStatus.UNRESOLVED, expected_scope=ClaimScope.SECTOR,
        domain_notes="Deliberate UNRESOLVED placeholder that prohibits unsupported "
                     "universality claims. A CTC verdict requires a specific "
                     "published construction to be instantiated with its route "
                     "geometry, velocities, synchronisation and matching data, and "
                     "then validated.",
        provenance=Provenance(("R12", "R13"), implementation_status="placeholder"),
        metadata={"role": "unresolved_placeholder"})


# ==========================================================================
# M23/M24 Anti-de Sitter pair -- the executable L3 gate
# ==========================================================================

def _ads4_metric():
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    L = sp.symbols("L", positive=True)
    f = 1 + r ** 2 / L ** 2
    g = sp.diag(-f, 1 / f, r ** 2, r ** 2 * sp.sin(th) ** 2)
    return (t, r, th, ph), L, g


def ads4_universal_cover() -> MetricModel:
    (t, r, th, ph), L, g = _ads4_metric()
    return MetricModel(
        id="ads4_universal_cover", title="M23 AdS4, universal cover (t in R)",
        coords=(t, r, th, ph), params=(L,), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR with Lambda = -3/L^2",
        matter=MatterSpec("vacuum with a negative cosmological constant",
                           vacuum=True, cosmological_constant=-3 / L ** 2),
        topology="R (time) x R^3; simply connected in the time direction",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.GLOBAL,
        temporal_function=t,
        domain=(_dom("radial", r, False), _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": 1.0, "theta": float(sp.pi / 2), "phi": 0.0,
                        "L": 1.0},
        domain_notes="g^tt = -1/(1 + r^2/L^2) < 0 everywhere, so t is an exact "
                     "global temporal function and the spacetime is stably causal. "
                     "This is the CHRONAL member of the AdS pair.",
        provenance=Provenance(("R26", "R27"),
                               "global AdS4 chart; the universal cover unwraps the "
                               "periodic time of the embedded hyperboloid"),
        metadata={"role": "L3_gate_pair", "pair": "ads4_periodic"})


def ads4_periodic() -> MetricModel:
    (t, r, th, ph), L, g = _ads4_metric()
    return MetricModel(
        id="ads4_periodic", title="M24 AdS4 hyperboloid, periodic time (t ~ t + 2 pi L)",
        coords=(t, r, th, ph), params=(L,), metric=g,
        compact=(CompactDirection(0, "t", 2 * sp.pi * L),
                 CompactDirection(3, "phi", 2 * pi)),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR with Lambda = -3/L^2",
        matter=MatterSpec("vacuum with a negative cosmological constant",
                           vacuum=True, cosmological_constant=-3 / L ** 2),
        topology="S^1 (time) x R^3; the embedded quadric in R^{2,3}",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.GLOBAL,
        quotient=Quotient(
            generators=(DeckTransformation(
                "time_shift", (t + 2 * sp.pi * L, r, th, ph),
                (t - 2 * sp.pi * L, r, th, ph),
                time_orientation_preserving=True,
                note="the closed timelike Killing orbit of the AdS quadric"),),
            label="Z generated by t -> t + 2 pi L", acts_freely=True),
        domain=(_dom("radial", r, False), _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": 1.0, "theta": float(sp.pi / 2), "phi": 0.0,
                        "L": 1.0},
        domain_notes="IDENTICAL local metric to ads4_universal_cover. The orbit of "
                     "the Killing vector d/dt is closed and timelike everywhere "
                     "(g_tt = -(1 + r^2/L^2) < 0), so every point lies on a CTC. "
                     "The two models differ ONLY in the deck group, which is exactly "
                     "the L3 scientific gate: local equality of metrics does not "
                     "imply equality of global causal structure.",
        provenance=Provenance(("R26", "R27"),
                               "AdS as a quadric in R^{2,3} has closed timelike "
                               "curves; the universal cover removes them"),
        metadata={"role": "L3_gate_pair", "pair": "ads4_universal_cover"})


def minkowski_time_periodic() -> MetricModel:
    """M30: the minimal possible CTC spacetime, used as a positive control for
    the topology engine and as a unit test that the temporal-function
    certificate is refused when tau is not single valued on the quotient."""
    t, x, y, z = sp.symbols("t x y z", real=True)
    P = sp.symbols("P", positive=True)
    g = sp.diag(-1, 1, 1, 1)
    return MetricModel(
        id="minkowski_time_periodic",
        title="M30 Minkowski with periodic time (t ~ t + P)",
        coords=(t, x, y, z), params=(P,), metric=g,
        compact=(CompactDirection(0, "t", P),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR",
        matter=MatterSpec("vacuum", T=sp.zeros(4, 4), vacuum=True),
        topology="S^1 x R^3",
        expected=CTCStatus.CTC_PROVED, expected_scope=ClaimScope.GLOBAL,
        quotient=Quotient((DeckTransformation(
            "time_shift", (t + P, x, y, z), (t - P, x, y, z),
            time_orientation_preserving=True),),
            label="Z generated by t -> t + P", acts_freely=True),
        default_point={"t": 0.0, "x": 0.0, "y": 0.0, "z": 0.0, "P": 1.0},
        domain_notes="Local metric identical to Minkowski, which is the strongest "
                     "no-CTC control in the registry. The only difference is the "
                     "deck group. Any architecture that classifies these two the "
                     "same has failed the L3 gate.",
        provenance=Provenance(("R26", "R27")),
        metadata={"role": "L3_gate_pair", "pair": "minkowski", "flat_covering": True})


# ==========================================================================
# M25 de Sitter static patch
# ==========================================================================

def de_sitter_static() -> MetricModel:
    t, r, th, ph = sp.symbols("t r theta phi", real=True)
    L = sp.symbols("L", positive=True)
    f = 1 - r ** 2 / L ** 2
    g = sp.diag(-f, 1 / f, r ** 2, r ** 2 * sp.sin(th) ** 2)
    return MetricModel(
        id="de_sitter_static", title="M25 de Sitter, static patch",
        coords=(t, r, th, ph), params=(L,), metric=g,
        compact=(CompactDirection(3, "phi", 2 * pi),),
        kind=ModelKind.LOCAL_METRIC, theory="GR with Lambda = +3/L^2",
        matter=MatterSpec("vacuum with a positive cosmological constant",
                           vacuum=True, cosmological_constant=3 / L ** 2),
        topology="static patch chart; phi ~ phi + 2 pi",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        temporal_function=t,
        domain=(_dom("inside_horizon", L - r, True),
                _dom("radial", r, False),
                _dom("polar_regular", sp.sin(th), True)),
        default_point={"t": 0.0, "r": 0.5, "theta": float(sp.pi / 2), "phi": 0.0,
                        "L": 1.0},
        domain_notes="Positive-Lambda control. r = L is a cosmological horizon, "
                     "not a chronology horizon; the static t is a temporal function "
                     "only inside it, exactly as for Schwarzschild outside r = 2M.",
        provenance=Provenance(("R26", "R27")),
        metadata={"role": "positive_lambda_control", "horizon": "r = L"})


# ==========================================================================
# M29 Rotating BTZ (2+1)
# ==========================================================================

def btz_rotating() -> MetricModel:
    t, r, ph = sp.symbols("t r phi", real=True)
    Mb, Jb, ell = sp.symbols("M_BTZ J_BTZ ell", positive=True)
    N2 = -Mb + r ** 2 / ell ** 2 + Jb ** 2 / (4 * r ** 2)
    Nphi = -Jb / (2 * r ** 2)
    gtt = -N2 + r ** 2 * Nphi ** 2
    gtph = r ** 2 * Nphi
    g = sp.Matrix([[gtt, 0, gtph],
                   [0, 1 / N2, 0],
                   [gtph, 0, r ** 2]])
    return MetricModel(
        id="btz_rotating", title="M29 Rotating BTZ black hole (2+1)",
        coords=(t, r, ph), params=(Mb, Jb, ell), metric=sp.simplify(g),
        signature=(1, 0, 2),
        compact=(CompactDirection(2, "phi", 2 * pi),),
        kind=ModelKind.QUOTIENT_GLOBAL, theory="GR in 2+1 with Lambda = -1/ell^2",
        matter=MatterSpec("vacuum with a negative cosmological constant",
                           vacuum=True, cosmological_constant=-1 / ell ** 2),
        topology="quotient of AdS3 by a discrete boost; phi ~ phi + 2 pi",
        expected=CTCStatus.NO_CTC_CERTIFIED, expected_scope=ClaimScope.DECLARED_DOMAIN,
        domain=(_dom("radial", r, True),
                _dom("outside_outer_horizon",
                     N2, True),
                _dom("subextremal", Mb ** 2 * ell ** 2 - Jb ** 2, True)),
        default_point={"t": 0.0, "r": 3.0, "phi": 0.0,
                        "M_BTZ": 1.0, "J_BTZ": 0.5, "ell": 1.0},
        domain_notes="On the standard chart g_phi_phi = r^2 > 0, so the azimuthal "
                     "sector is spacelike everywhere. The chronology-violating "
                     "region of the maximally extended BTZ geometry sits at "
                     "r^2 < 0 and is EXCISED BY DEFINITION of the spacetime -- "
                     "exactly as the Kerr CTC region is retained by definition. "
                     "Registered as a control for the claim 'a quotient of AdS is "
                     "automatically causality violating', which is false.",
        provenance=Provenance(("R26", "R27"),
                               "Banados-Teitelboim-Zanelli black hole; standard "
                               "exterior chart"),
        metadata={"role": "excision_control", "excised_region": "r^2 < 0"})


# ==========================================================================
# Registry assembly
# ==========================================================================

_BUILDERS = (
    minkowski, flrw_flat, flrw_exponential, schwarzschild, reissner_nordstrom,
    kerr, kerr_extremal, kerr_newman, godel_type, godel, godel_critical,
    van_stockum, tipler_cylinder, taub_nut, misner, misner_covering, grant_space,
    spinning_cosmic_string, gott_two_strings, morris_thorne, time_shifted_wormhole,
    ori_2005, ori_2007_core, pseudo_reissner_nordstrom, ori_2007_full, alcubierre,
    krasnikov, paired_warp, ads4_universal_cover, ads4_periodic,
    minkowski_time_periodic, de_sitter_static, btz_rotating,
)


def all_models() -> dict[str, MetricModel]:
    out: dict[str, MetricModel] = {}
    for b in _BUILDERS:
        m = b()
        if m.id in out:
            raise ValueError(f"duplicate model id {m.id}")
        out[m.id] = m
    return out


__all__ = ["all_models"] + [b.__name__ for b in _BUILDERS]
